// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2_A_-2Zt68IxeIGMRGwtNfwzPXLc3gw',
    appId: '1:79978435586:web:d8d45d072c2cf246bcc31b',
    messagingSenderId: '79978435586',
    projectId: 'footballtickket',
    authDomain: 'footballtickket.firebaseapp.com',
    storageBucket: 'footballtickket.firebasestorage.app',
    measurementId: 'G-M1LTQC0YNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmcXPRoCFNZHIDuQUh8pG377nASSBEKPY',
    appId: '1:79978435586:android:ccf7ae7471206f64bcc31b',
    messagingSenderId: '79978435586',
    projectId: 'footballtickket',
    storageBucket: 'footballtickket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBofZtk7EuGTp6eCbDAl8q-Fcet_Og4Dgs',
    appId: '1:79978435586:ios:2352fa1bddfb58f6bcc31b',
    messagingSenderId: '79978435586',
    projectId: 'footballtickket',
    storageBucket: 'footballtickket.firebasestorage.app',
    iosClientId: '79978435586-oc04i32d925ne6386v0170a8hj2pcg34.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballTicket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBofZtk7EuGTp6eCbDAl8q-Fcet_Og4Dgs',
    appId: '1:79978435586:ios:2352fa1bddfb58f6bcc31b',
    messagingSenderId: '79978435586',
    projectId: 'footballtickket',
    storageBucket: 'footballtickket.firebasestorage.app',
    iosClientId: '79978435586-oc04i32d925ne6386v0170a8hj2pcg34.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballTicket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD2_A_-2Zt68IxeIGMRGwtNfwzPXLc3gw',
    appId: '1:79978435586:web:75a967a1fef9f898bcc31b',
    messagingSenderId: '79978435586',
    projectId: 'footballtickket',
    authDomain: 'footballtickket.firebaseapp.com',
    storageBucket: 'footballtickket.firebasestorage.app',
    measurementId: 'G-D2R2QD8YZZ',
  );
}
